### PR TITLE
New Shop data storage system & bug fixes

### LINKED ISSUE #68: [BUG] InventoryMoveItemEvent error with composters and hoppers
[download]: https://www.spigotmc.org/resources/tradeshop.32762/

Explanation of the label system for Issues may be found [here](https://github.com/SparklingComet/TradeShop/wiki/Issue-&-Pull-Request-labels).

## General Troubleshooting

Hey there! Before you report a bug,
  please make sure to follow these steps first!
  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest TradeShop version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Description

I noticed that whenever a piece of bonemeal is taken from a full composter by a hopper, TradeShop throws an error in the console. Neither the composter or the hopper had any sort of sign on them.
Any ideas on why this could be happening, and are there any workarounds in the meantime?

### Console Error

<details> 
  <summary> </summary>

`
[09:23:51] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to TradeShop v2.1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.a(TileEntityHopper.java:308) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.lambda$3(TileEntityHopper.java:270) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at java.util.stream.MatchOps$2MatchSink.accept(MatchOps.java:119) ~[?:?]
	at java.util.Spliterators$IntArraySpliterator.tryAdvance(Spliterators.java:1041) ~[?:?]
	at java.util.stream.IntPipeline.forEachWithCancel(IntPipeline.java:163) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.IntPipeline.anyMatch(IntPipeline.java:513) ~[?:?]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.a(TileEntityHopper.java:269) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.lambda$0(TileEntityHopper.java:118) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.a(TileEntityHopper.java:139) [spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.tick(TileEntityHopper.java:117) [spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.World.tickBlockEntities(World.java:670) [spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:402) [spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1068) [spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.NullPointerException
	at org.shanerx.tradeshop.listeners.ShopProtectionListener.onInventoryMoveItem(ShopProtectionListener.java:72) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	... 26 more
`

</details>

## Credits & Disclaimer

This file contains parts that were taken from [the JDA project](https://github.com/DV8FromTheWorld/JDA).
We do **not** wish to take credit for those parts.
Everything is licensed under the [Apache License v2.0](https://github.com/SparklingComet/TradeShop/blob/master/LICENSE).

### LINKED ISSUE #70: [BUG] Chests retain unique identifier when broken before trade sign
Chests with a trade sign on them are renamed to act as a unique identifier (I presume). When the sign is destroyed, the chest has this identifier removed. 

If the chest is destroyed with the sign still attached, the chest will retain this identifier. If this chest is placed down again and has a sign placed on it to create a new shop, the sign will throw a "no inventory available" error meaning unless the player renames it in an anvil, it can't be used to make another shop.

I've had some players accidentally do this, and obviously not understand why their shop isn't working.

### LINKED ISSUE #73: [BUG] Existing Tradeshop signs attempt to link to all newly placed containers neraby
By placing a new container near an existing TradeShop sign, the sign links to that new container. This can result in several issues:

1. You cannot create a new TradeShop next to an existing one.
2. Placing and then removing the new container will break the existing TradeShop. The existing shop will become closed, and if you attempt to open it with `/ts open`, you will receive the error `Your shop is missing a chest`. This occurs even if the existing shop is a double chest. Removing and replacing the TradeShop sign on the existing shop does fix this. However, if the existing shop is a double chest, this would remove protections on the second half of the double chest, as shop protections is currently build order dependent as described in #70:

>  Currently, double chest protection is dependent on the order in which you place the chests and tradeshop sign. If you place chest 1, then make a sign, then chest 2, then as described above, they will be considered the same inventory block. However, if you place both chests to create a double chest, and then add the tradeshop sign, you can add two tradeshop signs to the double chest. This has an upside and a downside. The downside is that if a user sets up their chest this way, but doesnt put down a second sign, the side of the double chest without a sign is vulnerable to being broken.

  The user would have to break the 2nd half of the chest, replace the sign, and then replace the 2nd half of the chest in order to re-enable protections, and this would cause any contents in the 2nd half of the chest to spew out.

3. If you do attempt to create a new TradeShop sign on a linked container, it will result in an invalid sign (Trade will be in red text). This then opens up the bug described in #70 where the existing shop could retain its named ID if destroyed before the shop sign. However, if 2.3 moves away from naming containers, as proposed in #70, then this point will be solved.

### LINKED ISSUE #75: [FEATURE] order-independent shulkers
Currently, when shulkers containing multiple items are added as a tradeshop product, the order of the items in the shulkers must be exactly the same as the shulker used to create the shop. So if a shulker had 2 different items swapped inside, the shulker wouldn't count be counted as part of the shop's stock. Not a deal breaker but a bit annoying if you're trying to sell a kit of items.

Perhaps when the shop is determining if there is sufficient stock, it could compare a sorted dictionary of item/qtys if a filled shulker was specified as the product, rather than the exact metadata?

### LINKED ISSUE #77: [FEATURE] Add option to allow trading with own shops (primarily for testing/debug)
An option to allow owners to purchase from their own shops, primarily for debugging/testing purposes, by both users and admins.

Could even be a change of the "You cant buy from a shop in which you're a user" to include a confirmation option. Something like:
"You are a user of this shop, are you sure you want to trade? [confirm]"

### LINKED ISSUE #79: [BUG] signed books not properly usable as products or costs
Server I play on is currently running 2.2.0-BETA, When testing how to create a voucher-like system which would allow the use of an item that could only have been created by the shop owner, I looked to signed books as an option. Tradeshop allows the usage of `/ts setcost 1` and `/ts setproduct 1` when holding the specific book, and the specific book shows up properly in the `/ts what` GUI, however it does not properly interact in the store.

If used as a cost,  the shop does not recognize the item in the inventory, and gives an error along the lines of "you do not have 1 written_book".

If used as a product, the shop does not recognize the item in the container as being the product being sold, and if interacted with automatically closes the shop, as it is considered to not have inventory.

### LINKED ISSUE #80: [BUG] [2.2.2 BETA] Shop chests can be opened by non-shop owners
tradeshop-2.2.2-BETA-2020-05-19T18.50.13.jar

Currently running Paper 300

image

### LINKED ISSUE #81: [BUG] [2.2.2 BETA] iTrade shops cannot be destroyed
tradeshop-2.2.2-BETA-2020-05-19T18.50.13.jar

itrade signs simply re-appear when destroyed. They can only be destroyed by removing the block they're attached to

On break:
https://pastebin.com/C8hB7kd8

### LINKED ISSUE #84: [BUG] Null Pointer Exception in Console when using TS WHAT
https://hatebin.com/vgdtehtcuq
A null pointer pops up in console sometimes when using /ts what.
The issue seems to arrive when no shop is in range or a player uses /ts what in the open.

### PR DESCRIPTION
**Pull request by KillerOfPie**
Xanth3r is going to test some more for me but im pretty sure this is well flushed out now, give it a look and let me know if you have questions.

[contributing]: https://github.com/SparklingComet/TradeShop/blob/master/.github/CONTRIBUTING.md

## Pull Request Etiquette

There are several guidelines you should follow in order for your
  Pull Request to be merged.

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

> It is sometimes better to include more changes in a single commit. 
  If you find yourself having an overwhelming amount of commits, you
  can **rebase** your branch.

### Pull Request

Replace this sentence with general description of what your Pull Request does.

### CODE REVIEW

**Comment by KillerOfPie** [comment]
this should fix #68, #70,  #73

**Comment by KillerOfPie** [comment]
Everything should be tested and good now

File: src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java [hunk 1]
```diff
@@ -236,69 +208,52 @@ public void onChestOpen(PlayerInteractEvent e) {
...
-            }
-
-            ShopChest shopOtherHalf = new ShopChest(otherhalf.getLocation());
-
-            if (shopOtherHalf.hasOwner() && !shopOtherHalf.getOwner().equals(p.getUniqueId())) {
-                event.setCancelled(true);
-                return;
-            }
-
-            new ShopChest(block, shopOtherHalf.getOwner(), shopOtherHalf.getShopSign().getLocation()).setEventName(event);
```
Comment (SparklingComet) [inline src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java:299]: why exactly do we not need this anymore?

File: src/main/java/org/shanerx/tradeshop/listeners/ShopTradeListener.java [hunk 2]
```diff
@@ -69,8 +68,13 @@ public void onBlockInteract(PlayerInteractEvent e) {
         JsonConfiguration json = new JsonConfiguration(s.getChunk());
         shop = json.loadShop(new ShopLocation(s.getLocation()));
 
-        if (shop == null)
+        if (shop == null) {
+            s.setLine(0, "");
+            s.setLine(1, "");
+            s.setLine(2, "");
+            s.setLine(3, "");
```
Comment (SparklingComet) [inline src/main/java/org/shanerx/tradeshop/listeners/ShopTradeListener.java:80]: why is the sign being modified here? Also, why is `Sign#update()` not being called after sign modification?

File: src/main/java/org/shanerx/tradeshop/objects/ShopChest.java [hunk 3]
```diff
@@ -68,36 +68,82 @@ public ShopChest(Block chest, UUID owner, Location sign) {
...
 	public static boolean isShopChest(Block checking) {
-		return checking != null &&
-				plugin.getListManager().isInventory(checking) &&
-				((Nameable) checking.getState()).getCustomName() != null &&
-				((Nameable) checking.getState()).getCustomName().contains("$ ^Sign:l_");
+        try {
+            if (isDoubleChest(checking)) {
+                DoubleChest dbl = getDoubleChest(checking);
+                return ((Container) dbl.getLeftSide().getInventory().getLocation().getBlock()).getPersistentDataContainer().has(plugin.getStorageKey(), PersistentDataType.STRING) ||
+                        ((Container) dbl.getRightSide().getInventory().getLocation().getBlock()).getPersistentDataContainer().has(plugin.getStorageKey(), PersistentDataType.STRING);
```
Comment (SparklingComet) [inline src/main/java/org/shanerx/tradeshop/objects/ShopChest.java]: ingenious use of PDC, I guess

File: src/main/java/org/shanerx/tradeshop/objects/ShopChest.java [hunk 4]
```diff
@@ -68,36 +68,82 @@ public ShopChest(Block chest, UUID owner, Location sign) {
...
+                        ((Nameable) stateLeft).setCustomName(((Nameable) stateLeft).getCustomName().split("\\$ \\^")[0]);
+                        stateLeft.update();
+                    }
+
+                } else if (((Nameable) bs).getCustomName().contains("$ ^Sign:l_")) {
+                    ((Nameable) bs).setCustomName(((Nameable) bs).getCustomName().split("\\$ \\^")[0]);
+                    bs.update();
+                }
+            }
+        }
```
Comment (SparklingComet) [inline src/main/java/org/shanerx/tradeshop/objects/ShopChest.java:114]: what exactly is happening here?

File: src/main/java/org/shanerx/tradeshop/TradeShop.java [hunk 5]
```diff
@@ -42,6 +43,18 @@
 
 public class TradeShop extends JavaPlugin {
 
+
+	private NamespacedKey storageKey = new NamespacedKey(this, "tradeshop-storage-data");
+	private NamespacedKey signKey = new NamespacedKey(this, "tradeshop-sign-data");
```
Comment (SparklingComet) [inline src/main/java/org/shanerx/tradeshop/TradeShop.java]: just technicality, make `final` maybe?

File: src/main/java/org/shanerx/tradeshop/listeners/CustomInventoryListener.java [hunk 6]
```diff
@@ -27,14 +27,15 @@
...
+import org.bukkit.event.EventPriority;
 import org.bukkit.event.Listener;
 import org.bukkit.event.inventory.InventoryClickEvent;
 import org.bukkit.inventory.Inventory;
 import org.shanerx.tradeshop.utils.Utils;
 
 public class CustomInventoryListener extends Utils implements Listener {
 
-	@EventHandler
+    @EventHandler(priority = EventPriority.HIGHEST)
```
Comment (SparklingComet) [inline src/main/java/org/shanerx/tradeshop/listeners/CustomInventoryListener.java]: I know the `ignoreCancelled` flag does not seem to be working, but did you not put it here on purpose?

File: src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java [hunk 7]
```diff
@@ -144,79 +142,53 @@ public void onEntityExplodeItem(EntityExplodeEvent event) {
...
-            if (s == null) {
-                new ShopChest(block.getLocation()).resetName();
-                return;
-            }
-
-            if (!ShopType.isShop(s)) {
-                new ShopChest(block.getLocation()).resetName();
+        } else if (ShopChest.isShopChest(block)) {
+            shop = new ShopChest(block.getLocation()).getShop();
+            if (shop == null)
```
Comment (SparklingComet) [inline src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java:184]: sleek

File: src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java [hunk 8]
```diff
@@ -144,79 +142,53 @@ public void onEntityExplodeItem(EntityExplodeEvent event) {
...
+            if (player.hasPermission(Permissions.ADMIN.getPerm()) || player.getUniqueId().equals(shop.getOwner().getUUID())) {
+                PlayerShopDestroyEvent destroyEvent = new PlayerShopDestroyEvent(player, shop);
+                Bukkit.getPluginManager().callEvent(destroyEvent);
+                if (destroyEvent.isCancelled()) {
+                    event.setCancelled(true);
+                    return;
+                }
 
-            Shop shop = Shop.loadShop(s);
+                shop.getChestAsSC().resetName();
```
Comment (SparklingComet) [inline src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java:194]: sorry, but what exactly does this do? Remove the old chest name `$ ^Sign:...`, or something else?

File: src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java [hunk 9]
```diff
@@ -144,79 +142,53 @@ public void onEntityExplodeItem(EntityExplodeEvent event) {
...
+                if (shop.getShopSign() == null) {
+                    shop.remove();
                 } else {
-                    if (bs instanceof Nameable && ((Nameable) bs).getCustomName() != null
-                            && ((Nameable) bs).getCustomName().contains("$ ^Sign:l_")) {
-                        ((Nameable) bs).setCustomName(((Nameable) bs).getCustomName().split("\\$ \\^")[0]);
-
-                        bs.update();
-                    }
+                    shop.updateSign();
```
Comment (SparklingComet) [inline src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java:200]: what exactly is this for?

File: src/main/java/org/shanerx/tradeshop/objects/ShopChest.java [hunk 10]
```diff
@@ -157,48 +203,42 @@ public String getName() {
...
+        container.update();
 
-			bs.update();
+/*
+		if (isDoubleChest(chest)) {
+			Container container2 = (Container)getOtherHalfOfDoubleChest(chest).getState();
+			container2.getPersistentDataContainer().set(plugin.getStorageKey(), PersistentDataType.STRING, getName());
+			container2.update();
 		}
+*/
```
Comment (SparklingComet) [inline src/main/java/org/shanerx/tradeshop/objects/ShopChest.java:222]: why is the dchest part gone?

**Review by SparklingComet — COMMENTED** [review]
The changes so far are very good. Once the few bugs are fixed, this will make for a very good update.

File: src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java (hunk 1 above)
Comment (KillerOfPie) [reply src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java:299]: I dont know why this was removed, will add back in when fixing the protection bugs

File: src/main/java/org/shanerx/tradeshop/listeners/ShopTradeListener.java (hunk 2 above)
Comment (KillerOfPie) [reply src/main/java/org/shanerx/tradeshop/listeners/ShopTradeListener.java:80]: If a shop doesnt exist I am clearing the sign since it isnt linked to a shop, I did forget to update the sign tho, will add that in

File: src/main/java/org/shanerx/tradeshop/objects/ShopChest.java (hunk 4 above)
Comment (KillerOfPie) [reply src/main/java/org/shanerx/tradeshop/objects/ShopChest.java:114]: clearing out our old name from any block that is passed to this, if it's a double chest it clears both sides.

File: src/main/java/org/shanerx/tradeshop/objects/ShopChest.java (hunk 10 above)
Comment (KillerOfPie) [reply src/main/java/org/shanerx/tradeshop/objects/ShopChest.java:222]: Wasn't sure if i needed to add the item to both sides of a double chest

File: src/main/java/org/shanerx/tradeshop/TradeShop.java (hunk 5 above)
Comment (KillerOfPie) [reply src/main/java/org/shanerx/tradeshop/TradeShop.java]: yes, will do

File: src/main/java/org/shanerx/tradeshop/listeners/CustomInventoryListener.java (hunk 6 above)
Comment (KillerOfPie) [reply src/main/java/org/shanerx/tradeshop/listeners/CustomInventoryListener.java]: yes because i do want to check it no matter what since its checking for our own inventory

File: src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java (hunk 7 above)
Comment (KillerOfPie) [reply src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java:184]: this was added a bit ago, just didn't get it everywhere

File: src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java (hunk 8 above)
Comment (KillerOfPie) [reply src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java:194]: yes, removes the old chestnames

File: src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java (hunk 9 above)
Comment (KillerOfPie) [reply src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java:200]: updates the text on the sign when the chest is broken, including status and everything

**Review by KillerOfPie — COMMENTED** [review]
@SparklingComet Resolve any items that I gave a sufficient answer on.

File: src/main/java/org/shanerx/tradeshop/listeners/ShopTradeListener.java (hunk 2 above)
Comment (SparklingComet) [reply src/main/java/org/shanerx/tradeshop/listeners/ShopTradeListener.java:80]: mhm.. and under which circumstances would this

```
if (ShopType.isShop(e.getClickedBlock())) {
            s = (Sign) e.getClickedBlock().getState();
        }
```

run, and yet the sign not be connected to a valid shop?

File: src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java (hunk 8 above)
Comment (SparklingComet) [reply src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java:194]: are names of other (shop-)chests reset as well or only the ones that are broken?

File: src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java (hunk 9 above)
Comment (SparklingComet) [reply src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java:200]: ty for clarifying

File: src/main/java/org/shanerx/tradeshop/listeners/CustomInventoryListener.java (hunk 6 above)
Comment (SparklingComet) [reply src/main/java/org/shanerx/tradeshop/listeners/CustomInventoryListener.java:38]: I guess, but what if some other plugin has anything to say about it?

File: src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java (hunk 8 above)
Comment (KillerOfPie) [reply src/main/java/org/shanerx/tradeshop/listeners/ShopProtectionListener.java:194]: This is in a couple places including the interact listener, so any shop that is interacted with should be reset if it still has one of our names

File: src/main/java/org/shanerx/tradeshop/listeners/ShopTradeListener.java (hunk 2 above)
Comment (KillerOfPie) [reply src/main/java/org/shanerx/tradeshop/listeners/ShopTradeListener.java:80]: XANT3R had an error come up where the shop sign existed but there was no shop in the config, which this prevents, should also clear the sign to prevent it from continuing to happen

File: src/main/java/org/shanerx/tradeshop/commands/CommandRunner.java [hunk 11]
```diff
@@ -910,8 +910,12 @@ public void multi() {
 	 * @return null if Shop is not found, Shop object if it is
 	 */
 	private Shop findShop() {
-		Block b = pSender.getTargetBlockExact(Setting.MAX_EDIT_DISTANCE.getInt());
+		if (pSender == null) {
+			sendMessage(Message.PLAYER_ONLY_COMMAND.getPrefixed());
+			return null;
+		}
```
Comment (SparklingComet) [inline src/main/java/org/shanerx/tradeshop/commands/CommandRunner.java:862]: This fixes #84 and similar NPEs for other player-only subcommands

File: src/main/java/org/shanerx/tradeshop/listeners/ShopCreateListener.java [hunk 12]
```diff
@@ -124,17 +123,11 @@ public void onSignChange(SignChangeEvent event) {
 		ItemStack product = lineCheck(event.getLine(1)),
 				cost = lineCheck(event.getLine(2));
 
-		if (product != null)
+        if (product != null && shop.getProduct().size() == 0)
```
Comment (SparklingComet) [inline src/main/java/org/shanerx/tradeshop/listeners/ShopCreateListener.java]: Why `==0`?

File: src/main/java/org/shanerx/tradeshop/listeners/ShopCreateListener.java [hunk 13]
```diff
@@ -124,17 +123,11 @@ public void onSignChange(SignChangeEvent event) {
...
 			shop.setProduct(product);
 
-		if (cost != null)
+        if (cost != null && shop.getCost().size() == 0)
```
Comment (SparklingComet) [inline src/main/java/org/shanerx/tradeshop/listeners/ShopCreateListener.java]: Same Q here

File: src/main/java/org/shanerx/tradeshop/objects/ShopChest.java [hunk 14]
```diff
@@ -55,8 +55,7 @@
 	public ShopChest(Location chestLoc) {
 		this.loc = chestLoc;
 
-
-		getBlock();
+        getBlock();
```
Comment (SparklingComet) [inline src/main/java/org/shanerx/tradeshop/objects/ShopChest.java]: Indents are all wonky

File: src/main/java/org/shanerx/tradeshop/listeners/ShopCreateListener.java (hunk 12 above)
Comment (KillerOfPie) [reply src/main/java/org/shanerx/tradeshop/listeners/ShopCreateListener.java]: Because its checking if the array is  empty. I think #isEmpty() may be an alternative same with <1 but they all kinda do the same thing...
